name: CI for video notification

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Check out repository
      uses: actions/checkout@v2

    # Configura o ambiente Go
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.7'  # Substitua pela versão do Go que você está utilizando

    # Instala as dependências
    - name: Install dependencies
      run: |
        go mod tidy

    # Build do projeto
    - name: Build
      run: |
        go build -v ./...

    # Rodar os testes
    # - name: Run tests
    #   run: |
    #     go test -v ./...

    # Rodar Sonar
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    # Rodar Sonar Quality Gate
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      if: github.ref == 'refs/heads/main'
      with:
        pollingTimeoutSec: 600
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
