name: CI for video notification

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Check out repository
      uses: actions/checkout@v2

    # Configura o ambiente Go
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.7'  # Substitua pela versão do Go que você está utilizando

    # Instala as dependências
    - name: Install dependencies
      run: |
        go mod tidy

    # Build do projeto
    - name: Build
      run: |
        go build -v ./...

    # Rodar os testes
    # - name: Run tests
    #   run: |
    #     go test -v ./...
